apiVersion: v1
kind: Service
metadata:
  annotations:
    description: The JGroups ping port for clustering.
#    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  labels:
    app: ${project.artifactId}
    application: ${project.artifactId}
  name: ${project.artifactId}-ping
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
  - name: ping
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: ${project.artifactId}
    group: ${project.groupId}
    provider: fabric8
  sessionAffinity: None
  type: ClusterIP

