apiVersion: v1
kind: Service
metadata:
  labels:
    app: ${project.artifactId}
    group: ${project.groupId}
    provider: fabric8
    version: ${project.version}
  name: ${project.artifactId}
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ${project.artifactId}
    group: ${project.groupId}
    provider: fabric8
  sessionAffinity: None
  type: ClusterIP
